spring:
  application:
    name: zingzing-backend
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:500MB}
      max-request-size: ${MAX_REQUEST_SIZE:502MB}
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/zingzing?currentSchema=core}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:Haripur@1}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        default_schema: core
  flyway:
    enabled: true
    create-schemas: true
    default-schema: core
    schemas: core
    locations: classpath:db/migration

server:
  port: ${PORT:8080}

springdoc:
  api-docs:
    enabled: ${SWAGGER_ENABLED:false}
    path: /v3/api-docs
  swagger-ui:
    enabled: ${SWAGGER_ENABLED:false}
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
    deep-linking: true
  swagger-ui.csrf:
    enabled: false

logging:
  level:
    org.springframework.security: INFO
    com.chamcham.backend: INFO

security:
  jwt:
    secret: ${JWT_SECRET_BASE64:441065381746aeq9li8fbjg81d0lb4jjatpp72earjgk}
    expiration-ms: ${JWT_EXPIRATION_MS:900000}
  refresh:
    expiration-seconds: ${REFRESH_EXPIRATION_SECONDS:2592000}
  cookie:
    secure: ${COOKIE_SECURE:false}
    same-site: ${COOKIE_SAME_SITE:Strict}
    max-age-seconds: ${COOKIE_MAX_AGE:2592000}
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:4200,http://localhost:5173,http://localhost:4173,https://chumchum-frontend.vercel.app}
  oauth:
    google:
      client-ids: ${GOOGLE_CLIENT_IDS:44085381746-geq9li8fbig81d0lb4jjatpp72earjgk.apps.googleusercontent.com}
      token-info-url: ${GOOGLE_TOKEN_INFO_URL:https://oauth2.googleapis.com/tokeninfo}

app:
  frontend-base-url: ${FRONTEND_BASE_URL:http://localhost:3000}
  email:
    log-content: ${EMAIL_LOG_CONTENT:false}
  refunds:
    mock:
      webhook-secret: ${MOCK_REFUND_WEBHOOK_SECRET:JustSomeRandSecretForSMSRefund}
  uploads:
    dir: ${UPLOAD_DIR:./uploads}
    base-url: ${UPLOAD_BASE_URL:http://localhost:8080/uploads}
