package com.zingzing.backend.config;

import java.util.List;

public final class MarketMetadata {

    private MarketMetadata() {
    }

    public static final List<String> PAKISTAN_CITIES = List.of(
            "Karachi",
            "Lahore",
            "Islamabad",
            "Rawalpindi",
            "Faisalabad",
            "Multan",
            "Peshawar",
            "Quetta",
            "Hyderabad",
            "Gujranwala",
            "Sialkot",
            "Sargodha",
            "Bahawalpur",
            "Sukkur",
            "Larkana",
            "Mardan",
            "Abbottabad",
            "Abdul Hakim",
            "Adda Jahan Khan",
            "Ahmadpur East",
            "Ahmedpur Sial",
            "Akora Khattak",
            "Alipur",
            "Ali Pur Chattha",
            "Aliabad",
            "Arifwala",
            "Astore",
            "Attock",
            "Awaran",
            "Badin",
            "Bagh",
            "Bahawalnagar",
            "Bannu",
            "Barikot",
            "Batkhela",
            "Battagram",
            "Bela",
            "Bhakkar",
            "Bhalwal",
            "Bhan Saeedabad",
            "Bhera",
            "Bhimber",
            "Bhiria",
            "Burewala",
            "Chak Jhumra",
            "Chakdara",
            "Chakwal",
            "Chaman",
            "Charsadda",
            "Chawinda",
            "Chenab Nagar",
            "Chichawatni",
            "Chilas",
            "Chiniot",
            "Chishtian",
            "Chitral",
            "Choa Saidan Shah",
            "Chor",
            "Chowk Azam",
            "Dadu",
            "Daharki",
            "Dalbandin",
            "Daska",
            "Daud Khel",
            "Daur",
            "Dera Allah Yar",
            "Dera Bugti",
            "Dera Ghazi Khan",
            "Dera Ismail Khan",
            "Dera Murad Jamali",
            "Dina",
            "Dipalpur",
            "Diplo",
            "Dokri",
            "Duki",
            "Fateh Jang",
            "Fatehpur",
            "Fort Abbas",
            "Gahkuch",
            "Gambat",
            "Garhi Khairo",
            "Ghotki",
            "Gilgit",
            "Gojra",
            "Gwadar",
            "Gujar Khan",
            "Gujrat",
            "Hafizabad",
            "Hala",
            "Hangu",
            "Haripur",
            "Haroonabad",
            "Hasilpur",
            "Hassan Abdal",
            "Haveli Lakha",
            "Hub",
            "Hujra Shah Muqim",
            "Hunza",
            "Jacobabad",
            "Jalalpur Jattan",
            "Jalalpur Pirwala",
            "Jampur",
            "Jamshoro",
            "Jaranwala",
            "Jatoi",
            "Jauharabad",
            "Jhang",
            "Jhelum",
            "Kabirwala",
            "Kahuta",
            "Kakul",
            "Kalat",
            "Kamalia",
            "Kamber Ali Khan",
            "Kamoke",
            "Kandhkot",
            "Kandiaro",
            "Karor Lal Esan",
            "Kashmore",
            "Kasur",
            "Khairpur",
            "Khairpur Nathan Shah",
            "Khanewal",
            "Khanpur",
            "Kharan",
            "Kharian",
            "Khaplu",
            "Khewra",
            "Khuzdar",
            "Kohat",
            "Kot Addu",
            "Kot Ghulam Muhammad",
            "Kot Momin",
            "Kot Radha Kishan",
            "Kotli",
            "Kotri",
            "Kundian",
            "Lakki Marwat",
            "Lalamusa",
            "Layyah",
            "Liaquatpur",
            "Lodhran",
            "Loralai",
            "Mailsi",
            "Makli",
            "Malakand",
            "Mandi Bahauddin",
            "Mansehra",
            "Mastung",
            "Matiari",
            "Matli",
            "Mehar",
            "Mehrabpur",
            "Mian Channu",
            "Mianwali",
            "Minchinabad",
            "Mingora",
            "Miran Shah",
            "Mirpur",
            "Mirpur Khas",
            "Mirpur Mathelo",
            "Mithi",
            "Moro",
            "Muridke",
            "Murree",
            "Muzaffarabad",
            "Muzaffargarh",
            "Nankana Sahib",
            "Narowal",
            "Nasirabad",
            "Naudero",
            "Naukot",
            "Nawabshah",
            "New Mirpur",
            "Nowshera",
            "Nushki",
            "Okara",
            "Pabbi",
            "Pakpattan",
            "Pano Aqil",
            "Pasrur",
            "Pattoki",
            "Phalia",
            "Pind Dadan Khan",
            "Pindi Bhattian",
            "Piplan",
            "Pir Mahal",
            "Qadirpur Ran",
            "Qila Abdullah",
            "Qila Saifullah",
            "Rahim Yar Khan",
            "Rajanpur",
            "Ratodero",
            "Rawalakot",
            "Renala Khurd",
            "Risalpur",
            "Rohri",
            "Sadiqabad",
            "Safdarabad",
            "Sahiwal",
            "Sakrand",
            "Sambrial",
            "Samundri",
            "Sanghar",
            "Sangla Hill",
            "Sehwan",
            "Shabqadar",
            "Shahdadkot",
            "Shahdadpur",
            "Shahkot",
            "Shakargarh",
            "Sheikhupura",
            "Shigar",
            "Shikarpur",
            "Shorkot",
            "Sibi",
            "Skardu",
            "Sujawal",
            "Swabi",
            "Swat",
            "Takht Bhai",
            "Talagang",
            "Tando Adam",
            "Tando Allahyar",
            "Tando Jam",
            "Tando Muhammad Khan",
            "Tank",
            "Taxila",
            "Thatta",
            "Timergara",
            "Toba Tek Singh",
            "Turbat",
            "Umerkot",
            "Upper Dir",
            "Usta Muhammad",
            "Vehari",
            "Wah Cantt",
            "Wana",
            "Warburton",
            "Wazirabad",
            "Zafarwal",
            "Zhob"
    );
}
